---
- name: Manjaro Awesome Workstation Playbook
  hosts: localhost
  become: yes
  # gather_facts: no
  roles:
    - { role: base, tags: ['base'] }
    - { role: aura, tags: ['aura'] }
    - { role: terminals, tags: ['terminals'] }
    - { role: gnupg, tags: ['gnupg'] }
    - { role: microcode, tags: ['microcode'], when: "'GenuineIntel' in ansible_processor" }
    - { role: ssh, tags: ['ssh'] }
    - { role: ssd, tags: ['ssd'] }
    - { role: lightdm, tags: ['lightdm'], when: "display_manager == 'lightdm'" }
    - { role: pass, tags: ['pass'] }
    - { role: nettools, tags: ['nettools'] }
    - { role: networkmanager, tags: ['networkmanager'] }
    - { role: filesystems, tags: ['filesystems'] }
    - { role: archive, tags: ['archive'] }
    - { role: udisks, tags: ['udisks'] }
    - { role: browsers, tags: ['browsers'] }
    - { role: pdf, tags: ['pdf'] }
    - { role: virtualbox, tags: ['virtualbox'] }
    - { role: hashicorp, tags: ['hashicorp'] }
    - { role: virtualenv, tags: ['virtualenv'] }
    - { role: borg, tags: ['borg'] }
    - { role: bluetooth, tags: ['bluetooth'], when: "bluetooth is defined" }
    - { role: hostsctl, tags: ['hostsctl'], when: "hostsctl is defined" }
    - { role: logitech, tags: ['logitech'] }
    - { role: vim, tags: ['vim'] }
    - { role: fonts, tags: ['fonts'] }
    - { role: x, tags: ['x'] }
    - { role: docker, tags: ['docker'] }
    - { role: virt-manager, tags: ['virtualbox'] }
    - { role: menus, tags: ['menus'] }
    - { role: nvm, tags: ['nvm'] }
    - { role: bitwarden, tags: [' '] }
    - { role: golang, tags: [' '] }
    - { role: spice, tags: [' '] }
    - { role: kvm, tags: [' '] }
    - { role: xen, tags: [' '] }

  vars_prompt:
    - name: user_password
      prompt: "Enter Password for User Configured During Install"
