---
- name: Install PulseAudio bluetooth with LDAC/aptX support
  command: /usr/bin/aura -Ax --noconfirm --needed  libldac
  tags:
    - aura

- name: Install bluetooth libraries and tools
  pacman:
    name:
      - bluez
      - bluez-libs
      - bluez-utils
      - blueman
    state: present

- name: Auto-switch between HSP/HSF and A2DP
  lineinfile:
      dest: /etc/pulse/default.pa
      regex: "^load-module module-bluetooth-policy"
      state: present
      line: "load-module module-bluetooth-policy auto_switch=2"


- name: Unblock the bluetooth service
  service: name="rfkill-block@bluetooth.service" enabled=no state=stopped
  when: bluetooth.disable == False

- name: Enable and start the bluetooth service
  service: name=bluetooth.service enabled=yes state=started
  when: bluetooth.disable == False

