---
- name: Install Xorg
  pacman: name=xorg-server state=present

- name: Install Xinit
  pacman: name=xorg-xinit state=present

- name: Install Spice
  pacman: name=spice state=present

- name: Install xmodmap
  pacman: name=xorg-xmodmap state=present

- name: Install xdpyinfo
  pacman: name=xorg-xdpyinfo state=present

- name: Install xev
  pacman: name=xorg-xev state=present

- name: Install xorg-sessreg
  pacman: name=xorg-sessreg state=present

- name: Install xautomation
  pacman: name=xautomation state=present

- name: Install xdmx
  pacman: name=xorg-server-xdmx state=present
- name: Install xnest
  pacman: name=xorg-server-xnest state=present


- name: Add user to video group
  user: name={{ user.name }} groups=video append=yes
  tags:
    - user

- name: Enable middle-click scrolling
  template: src=30-scroll.conf dest=/etc/X11/xorg.conf.d/30-scroll.conf
  when: libinput.middle_click_scroll is defined
  tags:
    - libinput

- name: Install Xorg Xauth
   pacman:
     name: xorg-xauth
     state: present

- name: Install Xorg Xhost
   pacman:
     name: xorg-xhost
     state: present

- include: sxhkd.yml
- include: unclutter.yml
- include: autorandr.yml
- include: srandrd.yml
- include: autocutsel.yml
- include: xdg.yml
