---
- name: Install vagrant
  pacman:
    name: vagrant
    state: present

- name: Install consul
  pacman:
    name: consul
    state: present

- name: Install terraform
  pacman:
    name: terraform
    state: present

- name: Install vault
  pacman:
    name: vault
    state: present

- name: Install nomad
  command: /usr/bin/aura -Ax --noconfirm --needed nomad
  tags:
    - aura
