---
- name: Install multilib-devel
   pacman:
    name: multilib-devel
    state: present

- name: Install OVMF
   pacman:
    name: ovmf
    state: present

- name: Install libvirt-xen
   command: /usr/bin/aura -Ax libvirt-xen

- name: Install Xen
   command: /usr/bin/aura -Ax xen

- name: Install Xen Docs
   command: /usr/bin/aura -Ax xen-docs
